# This is a basic workflow to compile APK flutter

name: Flutter APK CI

name: Flutter APK CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "### Hello Flutter CI! ###"

      - name: Configurate JAVA
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Flutter actions setup
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter doctor (diagnose)
        run: flutter doctor -v

      - name: Flutter No interactions
        run: flutter config --no-cli-animations
        working-directory: ./aparcamientoszaragoza

      - name: List repo root
        run: ls -la

      - name: Print working dir
        run: pwd

      - name: Flutter pub get
        run: flutter pub get
        working-directory: ./aparcamientoszaragoza

      - name: Flutter build apk
        run: flutter build apk --release
        working-directory: ./aparcamientoszaragoza

      - name: List apk output
        run: ls -la ./aparcamientoszaragoza/build/app/outputs/flutter-apk || true

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ./aparcamientoszaragoza/build/app/outputs/flutter-apk/app-release.apk
        working-directory: ./aparcamientoszaragoza

